trigger: ["master"]
pr: ["master"]

jobs:
# Check formatting
- job: rustfmt
  displayName: Check rustfmt
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: ci/azure-install-rust.yml
      parameters:
        platform: Linux
        # Pin the version of Rust in case rustfmt changes.
        rust_version: 1.32.0
    - bash: |
        rustup component add rustfmt
      displayName: Install rustfmt
    - bash: |
        cargo fmt --all -- --check
      displayName: Check formatting

# Basic test run on all platforms
- template: ci/azure-test-stable.yml
  parameters:
    name: Linux_Stable
    displayName: Linux + Stable Rust
    vmImage: ubuntu-16.04

- template: ci/azure-test-stable.yml
  parameters:
    name: MacOS_Stable
    displayName: OS X + Stable Rust
    vmImage: macOS-10.13

- template: ci/azure-test-stable.yml
  parameters:
    name: Windows_Stable
    displayName: Windows + Stable Rust
    vmImage: vs2017-win2016
