jobs:

- job: check_formatting
  displayName: Check formatting
  pool:
    vmImage: ubuntu-16.04
  steps:
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: Install Rust
    - script: |
        cargo fmt --all -- --check
      displayName: Check formatting
