jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - template: azure-install-rust.yml
    parameters:
      platform: ${{parameters.name}}
      rust_version: stable
  - bash: |
      # Limit the execution time of loom tests.
      export LOOM_MAX_DURATION=10
      cargo test --all
